services:
  scraper:
    build: .
    container_name: telegram_scraper
    restart: always
    env_file: .env
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./session:/app/session
      # - ./mtproto_session.session:/app/mtproto_session.session
